import React from 'react';
import {
  Wand2 as MagicWandIcon,
  BadgeHelp as LogoIcon,
  Loader2 as SpinnerIcon,
  PlusCircle as PlusIcon,
  Trash2 as TrashIcon,
  Link2 as LinkIcon,
  FileText as DocumentTextIcon,
  Volume2 as SpeakerWaveIcon,
  XCircle,
  Save,
  FolderOpen,
  FilePlus,
  Image as PhotoIcon,
  FileDown as DocumentArrowDownIcon,
  Code2 as CodeBracketIcon,
  Paintbrush2 as PaintBrushIcon,
  Users2 as UsersIcon,
  Bug as BugAntIcon,
  Megaphone,
  Rocket,
  Flag,
  File as FileIcon
} from 'lucide-react';

export {
  MagicWandIcon,
  LogoIcon,
  SpinnerIcon,
  PlusIcon,
  TrashIcon,
  LinkIcon,
  DocumentTextIcon,
  SpeakerWaveIcon,
  XCircle as XCircleIcon,
  Save as SaveIcon,
  FolderOpen as FolderOpenIcon,
  FilePlus as DocumentPlusIcon,
  PhotoIcon,
  DocumentArrowDownIcon,
  CodeBracketIcon,
  PaintBrushIcon,
  UsersIcon,
  BugAntIcon,
  Megaphone as MegaphoneIcon,
  Rocket as RocketLaunchIcon,
  Flag as FlagIcon,
  FileIcon
};
